# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Photon Design System
email: your-email@mozilla.com
description: > # this means to ignore newlines until "baseurl:"
  The Photon Design System houses guidelines, reusable UI components, templates,
  and other resources to help you create products for Firefox users.
baseurl: "/photon" # the subpath of your site, e.g. /blog
url: "https://design.firefox.com" # the base hostname & protocol for your site
twitter_username: firefoxux
github_username:  firefoxux

# Build settings
markdown: kramdown
